var Swapper=function(A,t,h,j){function u(a,b){var c=b.parentNode;c.lastchild===b?c.appendChild(a):c.insertBefore(a,b.nextSibling)}function r(a){a.parentNode&&a.parentNode.removeChild(a)}function k(a,b){a.style["-webkit-transform"]=b;a.style["-moz-transform"]=b;a.style["-ms-transform"]=b;a.style["-o-transform"]=b;a.style.transform=b}function o(a,b){b?(a.style["-webkit-transition"]="-webkit-"+b,a.style["-moz-transition"]="-moz-"+b,a.style["-ms-transition"]="-ms-"+b,a.style["-o-transition"]="-o-"+b,
a.style.transition=b):(a.style["-webkit-transition"]="",a.style["-moz-transition"]="",a.style["-ms-transition"]="",a.style["-o-transition"]="",a.style.transition="")}function p(a,b){var c;c=b?a.style:t.defaultView.getComputedStyle(a,null);return{display:c.display,opacity:c.opacity,top:c.top,left:c.left,height:c.height,width:c.width,position:c.position}}function v(a){var b;a:if(a){try{b=a instanceof Node||a instanceof HTMLElement;break a}catch(c){}b="object"!==typeof a||"number"!==typeof a.nodeType||
"string"!==typeof a.nodeName?!1:!0}else b=!1;if(!b)throw TypeError("element must be a DOM node, got "+a);}function i(a,b,c,n){function h(){d.addEventListener("webkitTransitionEnd",f,!1);d.addEventListener("transitionend",f,!1);d.addEventListener("oTransitionEnd",f,!1);d.addEventListener("otransitionend",f,!1);d.addEventListener("MSTransitionEnd",f,!1);d.addEventListener("transitionend",f,!1)}function f(){w||(w=!0,d&&(d.removeEventListener("webkitTransitionEnd",f),d.removeEventListener("transitionend",
f),d.removeEventListener("oTransitionEnd",f),d.removeEventListener("otransitionend",f),d.removeEventListener("MSTransitionEnd",f),d.removeEventListener("transitionend",f)),r(a),o(a,""),o(b,""),setTimeout(function(){k(a,"");k(b,"");if(e[0].fade)b.style.opacity=l.opacity;if(e[1].fade)a.style.opacity=z.opacity;b.style.position=l.position;b.style.top=l.top;b.style.left=l.left;b.style.height=l.height;b.style.width=l.width;a._swapper=false;b._swapper=false;n()},0))}v(a);v(b);"function"===typeof c&&(n=c,
c={});switch(typeof c){case "string":c={transition:c};break;case "undefined":c={};break;case "object":break;default:throw TypeError("options must be an object if defined, got "+c);}switch(typeof c.transition){case "string":if(!(c.transition in x)&&"instant"!==c.transition)throw TypeError(c.transition+" is not a valid transition");break;case "undefined":break;default:throw TypeError("transition must be a string if defined, got "+c.transition);}switch(typeof c.duration){case "number":if(0>c.duration)throw TypeError("duration must be a non-negative integer, got "+
c.duration);break;case "undefined":break;default:throw TypeError("duration must be a number if defined, got "+c.duration);}switch(typeof c.easing){case "string":if(!(c.easing in y))throw TypeError(c.easing+" is not a valid easing");break;case "undefined":break;default:throw TypeError("easing must be a string if defined, got "+c.easing);}var g=n;switch(typeof g){case "undefined":g=function(){};break;case "function":break;default:throw TypeError("callback must be a function if defined, got "+g);}n=
g;if(a._swapper)throw Error("elem1 is currently being swapped");if(b._swapper)throw Error("elem2 is currently being swapped");a:{for(g=a;g=g.parentNode;)if(g===t){g=!0;break a}g=!1}if(!g)throw Error("elem1 must be in the DOM to be swapped");a._swapper=!0;b._swapper=!0;r(b);if("instant"===c.transition)u(b,a),r(a),a._swapper=!1,b._swapper=!1,setTimeout(function(){n()},0);else{var e=x[c.transition||"fade"],j=y[c.easing||"ease-in-out"],i=c.duration||300;u(b,a);var c=a.getBoundingClientRect(),q=p(a),s=
p(b),z=p(a,!0),l=p(b,!0);"none"!==q.display&&(b.style.position="fixed",b.style.top=c.top+"px",b.style.left=c.left+"px");b.style.height=s.height||q.height;b.style.width=s.width||q.width;e[2]&&a.parentNode.insertBefore(b,a);k(a,m);k(b,e[0].transform||m);e[0].fade&&(b.style.opacity="0");e[1].fade&&(a.style.opacity="1");setTimeout(function(){var c="transform "+i/1E3+"s "+j+", opacity "+i/1E3+"s "+j;o(a,c);o(b,c);setTimeout(function(){k(a,e[1].transform||m);k(b,m);if(e[0].fade)b.style.opacity="1";if(e[1].fade)a.style.opacity=
"0";if(s.display!=="none"&&(e[0].fade||e[0].transform&&e[0].transform!==m)){d=b;h()}else if(q.display!=="none"&&(e[1].fade||e[1].transform&&e[1].transform!==m)){d=a;h()}else setTimeout(f,i)},0)},0);var w=!1,d}}var m="translate3d(0,0,0) scale(1)";/\bandroid\b/i.test(navigator.userAgent);var x={fade:[{fade:!0},{fade:!0}],"fade-on":[{fade:!0},{}],"fade-off":[{},{fade:!0},!0],"scale-in":[{transform:"scale(0.01)"},{}],"scale-out":[{},{transform:"scale(0.01)"},!0],"rotate-left":[{transform:"rotateY(-180deg) perspective(360px)",
fade:!0},{transform:"rotateY( 180deg) perspective(360px)",fade:!0}],"rotate-right":[{transform:"rotateY( 180deg) perspective(360px)",fade:!0},{transform:"rotateY(-180deg) perspective(360px)",fade:!0}],"cube-left":[{transform:"translate3d( 50%,0,0) rotateY(-90deg) perspective(360px)"},{transform:"translate3d(-50%,0,0) rotateY( 90deg) perspective(360px)"}],"cube-right":[{transform:"translate3d(-50%,0,0) rotateY( 90deg) perspective(360px)"},{transform:"translate3d( 50%,0,0) rotateY(-90deg) perspective(360px)"}],
"swap-left":[{transform:"translate3d( 65%,0,0) rotateY( 90deg) perspective(360px)"},{transform:"translate3d(-65%,0,0) rotateY(-90deg) perspective(360px)"}],"swap-right":[{transform:"translate3d(-65%,0,0) rotateY(-90deg) perspective(360px)"},{transform:"translate3d( 65%,0,0) rotateY( 90deg) perspective(360px)"}],"explode-in":[{fade:!0,transform:"scale(1.25)"},{}],"explode-out":[{},{fade:!0,transform:"scale(1.25)"},!0],"implode-in":[{},{fade:!0,transform:"scale(0.60)"},!0],"implode-out":[{fade:!0,transform:"scale(0.80)"},
{}],"slide-left":[{transform:"translate3d( 100%,0,0)"},{transform:"translate3d(-100%,0,0)"}],"slide-right":[{transform:"translate3d(-100%,0,0)"},{transform:"translate3d( 100%,0,0)"}],"slide-up":[{transform:"translate3d(0, 100%,0)"},{transform:"translate3d(0,-100%,0)"}],"slide-down":[{transform:"translate3d(0,-100%,0)"},{transform:"translate3d(0, 100%,0)"}],"slideon-left":[{transform:"translate3d(-100%,0,0)"},{}],"slideoff-left":[{},{transform:"translate3d(-100%,0,0)"},!0],"slideon-right":[{transform:"translate3d(100%,0,0)"},
{}],"slideoff-right":[{},{transform:"translate3d(100%,0,0)"},!0],"slideon-up":[{transform:"translate3d(0,-100%,0)"},{}],"slideoff-up":[{},{transform:"translate3d(0,-100%,0)"},!0],"slideon-down":[{transform:"translate3d(0,100%,0)"},{}],"slideoff-down":[{},{transform:"translate3d(0,100%,0)"},!0]},y={linear:"linear",ease:"ease","ease-in":"ease-in","ease-out":"ease-out","ease-in-out":"ease-in-out","step-start":"step-start","step-end":"step-end"};h&&h.extend(h.fn,{swapper:function(a,b,c){a=h(a)[0];this.forEach(function(h){i(h,
a,b,c)});return this}});j&&(j.fn.swapper=function(a,b,c){a=j(a)[0];this.each(function(){i(this,a,b,c)});return this});return i}(window,document,window.Zepto,window.jQuery);
